package com.nkcs.ereader.base.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.nkcs.ereader.base.entity.Chapter;

import com.nkcs.ereader.base.entity.Book;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BOOK".
*/
public class BookDao extends AbstractDao<Book, Long> {

    public static final String TABLENAME = "BOOK";

    /**
     * Properties of entity Book.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Hash = new Property(2, String.class, "hash", false, "HASH");
        public final static Property Cover = new Property(3, String.class, "cover", false, "COVER");
        public final static Property TotalChapter = new Property(4, Integer.class, "totalChapter", false, "TOTAL_CHAPTER");
        public final static Property HasFormat = new Property(5, Boolean.class, "hasFormat", false, "HAS_FORMAT");
        public final static Property Created = new Property(6, java.util.Date.class, "created", false, "CREATED");
        public final static Property Progress = new Property(7, Double.class, "progress", false, "PROGRESS");
    }

    private DaoSession daoSession;


    public BookDao(DaoConfig config) {
        super(config);
    }
    
    public BookDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BOOK\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TITLE\" TEXT," + // 1: title
                "\"HASH\" TEXT," + // 2: hash
                "\"COVER\" TEXT," + // 3: cover
                "\"TOTAL_CHAPTER\" INTEGER," + // 4: totalChapter
                "\"HAS_FORMAT\" INTEGER," + // 5: hasFormat
                "\"CREATED\" INTEGER," + // 6: created
                "\"PROGRESS\" REAL);"); // 7: progress
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_BOOK_HASH ON \"BOOK\"" +
                " (\"HASH\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BOOK\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Book entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String hash = entity.getHash();
        if (hash != null) {
            stmt.bindString(3, hash);
        }
 
        String cover = entity.getCover();
        if (cover != null) {
            stmt.bindString(4, cover);
        }
 
        Integer totalChapter = entity.getTotalChapter();
        if (totalChapter != null) {
            stmt.bindLong(5, totalChapter);
        }
 
        Boolean hasFormat = entity.getHasFormat();
        if (hasFormat != null) {
            stmt.bindLong(6, hasFormat ? 1L: 0L);
        }
 
        java.util.Date created = entity.getCreated();
        if (created != null) {
            stmt.bindLong(7, created.getTime());
        }
 
        Double progress = entity.getProgress();
        if (progress != null) {
            stmt.bindDouble(8, progress);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Book entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String hash = entity.getHash();
        if (hash != null) {
            stmt.bindString(3, hash);
        }
 
        String cover = entity.getCover();
        if (cover != null) {
            stmt.bindString(4, cover);
        }
 
        Integer totalChapter = entity.getTotalChapter();
        if (totalChapter != null) {
            stmt.bindLong(5, totalChapter);
        }
 
        Boolean hasFormat = entity.getHasFormat();
        if (hasFormat != null) {
            stmt.bindLong(6, hasFormat ? 1L: 0L);
        }
 
        java.util.Date created = entity.getCreated();
        if (created != null) {
            stmt.bindLong(7, created.getTime());
        }
 
        Double progress = entity.getProgress();
        if (progress != null) {
            stmt.bindDouble(8, progress);
        }
    }

    @Override
    protected final void attachEntity(Book entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Book readEntity(Cursor cursor, int offset) {
        Book entity = new Book( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // hash
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // cover
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // totalChapter
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0, // hasFormat
            cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)), // created
            cursor.isNull(offset + 7) ? null : cursor.getDouble(offset + 7) // progress
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Book entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setHash(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCover(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTotalChapter(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setHasFormat(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
        entity.setCreated(cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)));
        entity.setProgress(cursor.isNull(offset + 7) ? null : cursor.getDouble(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Book entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Book entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Book entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getChapterDao().getAllColumns());
            builder.append(" FROM BOOK T");
            builder.append(" LEFT JOIN CHAPTER T0 ON T.\"_id\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Book loadCurrentDeep(Cursor cursor, boolean lock) {
        Book entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Chapter lastRead = loadCurrentOther(daoSession.getChapterDao(), cursor, offset);
        entity.setLastRead(lastRead);

        return entity;    
    }

    public Book loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Book> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Book> list = new ArrayList<Book>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Book> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Book> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
